#!/bin/sh /etc/rc.common
START=60
USE_PROCD=1
PROG=/usr/sbin/smartdns-rs
CONF=/etc/smartdns/smartdns.conf
start_service() {
	procd_open_instance
	procd_set_param command $PROG -f -c $CONF
	procd_set_param respawn
	procd_set_param file $CONF
	procd_set_param stdout 1 # log to syslog
	procd_set_param stderr 1 
	procd_close_instance
}
